# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm6375-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a23xq,$(TARGET_DEVICE)),)

endif
